[package]
name = "tenere"
version = "0.8.0"
authors = ["pythops <contact@pythops.com>"]
license = "AGPL-3.0"
edition = "2021"
description = "TUI interface for LLMs written in Rust"
readme = "README.md"
homepage = "https://github.com/pythops/tenere"
repository = "https://github.com/pythops/tenere"

[dependencies]
crossterm = "0.26"
tui = { package = "ratatui", version = "0.24", features = ["all-widgets"] }
unicode-width = "0.1"
reqwest = { version = "0.11", default-features = false, features = [
  "blocking",
  "json",
  "rustls-tls",
] }
serde_json = "1"
ansi-to-tui = "3"

clap = { version = "4", features = ["derive", "cargo"] }
toml = { version = "0.7" }
serde = { version = "1", features = ["derive"] }
dirs = "5"
regex = "1"
colored = "2"
bat = "0.24"
syntect = "5"
