[package]
name = "tenere"
version = "0.7.0"
authors = ["pythops <contact@pythops.com>"]
license = "AGPLv3"
edition = "2021"
description = "TUI interface for LLMs written in Rust"
readme = "README.md"
homepage = "https://github.com/pythops/tenere"
repository = "https://github.com/pythops/tenere"

[dependencies]
crossterm = "0.26.1"
tui = { package = "ratatui", version = "0.22.0" }
unicode-width = "0.1.10"
reqwest = { version = "0.11", default-features = false, features = [
  "blocking",
  "json",
  "rustls-tls",
] }
serde_json = "1.0"
termimad = "0.20"
ansi-to-tui = "3.1.0"

clap = { version = "4", features = ["derive", "cargo"] }
toml = { version = "0.7" }
serde = { version = "1.0", features = ["derive"] }
dirs = "5.0.1"
regex = "1.9.3"
colored = "2.0.4"
