[package]
name = "tenere"
version = "0.10.0"
authors = ["pythops <contact@pythops.com>"]
license = "AGPL-3.0"
edition = "2021"
description = "TUI interface for LLMs written in Rust"
readme = "README.md"
homepage = "https://github.com/pythops/tenere"
repository = "https://github.com/pythops/tenere"

[dependencies]
crossterm = { version = "0.27", features = ["event-stream"] }
ratatui = { version = "0.25", features = ["all-widgets"] }
tui-textarea = { version = "0.4" }
unicode-width = "0.1"
reqwest = { version = "0.11", default-features = false, features = [
  "json",
  "rustls-tls",
] }
serde_json = "1"
ansi-to-tui = "3"

clap = { version = "4", features = ["derive", "cargo"] }
toml = { version = "0.8" }
serde = { version = "1", features = ["derive"] }
dirs = "5"
regex = "1"
bat = "0.24"
arboard = "3"
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
