[package]
name = "tenere"
version = "0.1.0"
authors = ["pythops <contact@pythops.com>"]
license = "AGPLv3"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
tui = { package = "ratatui", version = "0.20.1" }
unicode-width = "0.1.10"
reqwest = { version = "0.11", default-features = false, features = [
  "blocking",
  "json",
  "rustls-tls",
] }
serde_json = "1.0"
termimad = "0.20"
ansi-to-tui = "3.0.0"

clap = { version = "4", features = ["derive", "cargo"] }
